[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clippy]
command = "cargo"
args = ["clippy"]
dependencies = ["format"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["build"]

[tasks.prepare]
dependencies = ["test", "clippy"]

[tasks.gitadd]
command = "git"
args = ["add", "."]

[tasks.gitcommit]
command = "git"
args = ["commit", "-m", "${@}"]
dependencies = ["gitadd"]

[tasks.gitpush]
command = "git"
args = ["push"]
dependencies = ["gitcommit"]

[tasks.deploy]
command = "cargo"
args = ["shuttle", "deploy"]

[tasks.restart]
command = "cargo"
args = ["shuttle", "project", "restart"]

[tasks.run]
command = "cargo"
args = ["shuttle", "run"]

[tasks.front-serve]
workspace = false
cwd = "./front"
install_crate = "dioxus-cli"
command = "dx"
args = ["serve", "--port", "8000"]

[tasks.twstart]
workspace = false
script_runner = "@shell"
script = '''
cd front
npx tailwindcss -i ./input.css -o ./public/tailwind.css --watch
'''


[tasks.front-build]
workspace = false
script_runner = "@shell"
script = '''
# shuttle issue with static files
# location is different depending on the environment
rm -rf api/shuttle/static static
mkdir api/shuttle/static
mkdir static
cd front
dx build --release
# local development 
cp -r dist/* ../api/shuttle/static
# production
cp -r dist/* ../static
'''
